//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procedure_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedure
    {
        public string subject { get; set; }
        public System.TimeSpan startTime { get; set; }
        public System.DateTime examDate { get; set; }
        public int duration { get; set; }
        public string classRoom { get; set; }
        public string faculty { get; set; }
        public string status { get; set; }
    }
}
